export const countries = [
  { code: '+91', name: 'India' },
  { code: '+1', name: 'United States' },
  { code: '+44', name: 'United Kingdom' },
  { code: '+61', name: 'Australia' },
  { code: '+81', name: 'Japan' },
  { code: '+33', name: 'France' },
  { code: '+49', name: 'Germany' },
  { code: '+39', name: 'Italy' },
  { code: '+55', name: 'Brazil' },
  { code: '+7', name: 'Russia' },
  { code: '+34', name: 'Spain' },
  { code: '+86', name: 'China' },
  { code: '+82', name: 'South Korea' },
  { code: '+27', name: 'South Africa' },
  { code: '+20', name: 'Egypt' },
];